export default {
  createValidator: 'cosmos-sdk/MsgCreateValidator',
  editValidator: 'cosmos-sdk/MsgEditValidator',
  delegate: 'cosmos-sdk/MsgDelegate',
  undelegate: 'cosmos-sdk/MsgUndelegate',
  redelegate: 'cosmos-sdk/MsgBeginRedelegate',
  unjail: 'cosmos-sdk/MsgUnjail',
  submitProposal: 'cosmos-sdk/MsgSubmitProposal',
  deposit: 'cosmos-sdk/MsgDeposit',
  vote: 'cosmos-sdk/MsgVote',
  textProposal: 'gov/TextProposal',
  swUpgradeProposal: 'gov/SoftwareUpgradeProposal',
  withdrawDelegationReward: 'cosmos-sdk/MsgWithdrawDelegationReward',
  withdrawValidatorCommission: 'cosmos-sdk/MsgWithdrawValidatorCommission',
  modifyWithdrawAddress: 'cosmos-sdk/MsgModifyWithdrawAddress',
  verifyInvariant: 'cosmos-sdk/MsgVerifyInvariant',
  send: 'cosmos-sdk/MsgSend',
  multiSend: 'cosmos-sdk/MsgMultiSend',
  createTopic: 'aol/MsgCreateTopic',
  addWriter: 'aol/MsgAddWriter',
  addRecord: 'aol/MsgAddRecord',
  deleteWriter: 'aol/MsgDeleteWriter',
};

