export default {
  // send: 0,
  // addRecord: 1,
  // vest: 2,
  // withdrawVesting: 3,
  // becomeCandidate: 4,
  // quitCandidacy: 5,
  // vote: 6,
  // addCertification: 7,
  // revokeCertification: 8,
  send: 'binary',
  addRecord: 'add_record',
  vest: 'vest',
  withdrawVesting: 'withdraw_vesting',
  becomeCandidate: 'become_candidate',
  quitCandidacy: 'quit_candidacy',
  vote: 'vote',
  addCertification: 'add_certification',
  revokeCertification: 'revoke_certification',
};

